version: "3"
services:
  fastapi_app:
    image: 
    depends_on:
      - postgres
    ports:
      #If on the prod server the service listens on port 80
      - "80:8000"

    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    #No bind mounts on prod server
      # volumes:
    #   - ./:/usr/src/app/:ro 
      # ro option for read only volume. container won't be able to change the files
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_NAME=${DATABASE_HOSTNAME}
      - POSTGRES_DB=${DATABASE_USERNAME}
    volumes:
      - postgres-db:/var/lib/postgres/data

volumes:
  postgres-db:
  