"""new migration file

Revision ID: 1f497b9c9bc7
Revises: 10a7cab8c350
Create Date: 2021-12-04 00:05:11.850337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f497b9c9bc7'
down_revision = '10a7cab8c350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
